# -*- coding: utf-8 -*-
"""rf100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8IqN5bvRxjAtakwLem5GFw6KVRWSit2

# Roboflow 100 📸: A Rich, Multi-Domain Object Detection Benchmark

![rf100blog-mosaicthing](https://user-images.githubusercontent.com/15908060/202452898-9ca6b8f7-4805-4e8e-949a-6e080d7b94d2.jpg)

This repository implements the Roboflow 100 benchmark developed by [Roboflow](https://roboflow.com/). It contains code to download the dataset and reproduce
mAP values for YOLOv5 and YOLOv7 Fine-Tuning and GLIP Evaluation on 100 of Roboflow Universe
datasets.


*RF100 was sponsored with ❤️ by [Intel](https://www.intel.com/content/www/us/en/homepage.html)*

## RF100

`RF100` contains the following datasets, carefully chosen from more than 90'000 datasets hosted on our [universe hub](https://universe.roboflow.com/). The datasets are splitted in 7 categories: `Aerial`, `Videogames`, `Microscopic`, `Underwater`, `Documents`, `Electromagnetic` and `Real World`. 


| Category        | Datasets | Images  | Classes |
|-----------------|----------|---------|---------|
| Aerial          | 7        | 9683    | 24      |
| Videogames      | 7        | 11579   | 88      |
| Microscopic     | 11       | 13378   | 28      |
| Underwater      | 5        | 18003   | 39      |
| Documents       | 8        | 24813   | 90      |
| Electromagnetic | 12       | 36381   | 41      |
| Real World      | 50       | 110615  | 495     |
| **Total**           | **100**      | **224,714** | **805**     |

## confirm GPU access
"""

!nvidia-smi

"""## set ROBOFLOW_API_KEY"""

# Commented out IPython magic to ensure Python compatibility.
# %env ROBOFLOW_API_KEY="0a4WwzoVWX7OLQHdybod"

"""## pull RF100 repository"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/
!rm -rf roboflow-100-benchmark/
!git clone https://github.com/roboflow-ai/roboflow-100-benchmark.git

# %cd /content/roboflow-100-benchmark/
!git submodule update --init --recursive

!pip install roboflow --quiet

!ls -la

"""## Download all datasets"""

# !rm -rf /content/datasets/
# !scripts/download_datasets.sh -f yolov5 -l /content/datasets/

"""## Download selected dataset"""

!head -n 10 datasets_links_640.txt

!rm -rf /content/datasets/
!python scripts/download_dataset.py -p x-ray-rheumatology -v 2 -f yolov5 -l /content/datasets/

!ls /content/datasets/x-ray-rheumatology

dataset="/content/datasets/x-ray-rheumatology"

"""## Setup YOLOv7 training environment"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/roboflow-100-benchmark/yolov7-benchmark/yolov7/
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7_training.pt

!python train.py --img 640 --batch 8 --epochs 100 --name $dataset/results --data $dataset/data.yaml  --weights 'yolov7_training.pt' |& tee $dataset/logs.txt

!python test.py --data $dataset/data.yaml --img 640 --batch 16 --weights $dataset/results/weights/best.pt --name  $dataset --exist-ok |& tee $dataset/val_eval.txt